<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Connector.AzureDataLake\Connector.AzureDataLake.csproj" />
    <ProjectReference Include="..\Connector.DataLake.Common.Tests.Integration\Connector.DataLake.Common.Tests.Integration.csproj" />

  </ItemGroup>

</Project>
