<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ParquetSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Connector.OneLake\Connector.OneLake.csproj" />
    <ProjectReference Include="..\Connector.DataLake.Common.Tests.Integration\Connector.DataLake.Common.Tests.Integration.csproj" />
  </ItemGroup>

</Project>
