using CluedIn.Connector.FileStorage.Common;
using CluedIn.Core;
using CluedIn.Core.Crawling;
using CluedIn.Core.Providers;

using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CluedIn.Connector.FabricOpenMirroring;

public class OpenMirroringConnectorProvider : ConnectorProviderBase<OpenMirroringConnectorProvider>
{
    public OpenMirroringConnectorProvider([NotNull] ApplicationContext appContext,
        IOpenMirroringConfigurationConstants configuration, ILogger<OpenMirroringConnectorProvider> logger)
        : base(appContext, configuration, logger)
    {
    }

    protected override IEnumerable<string> ProviderNameParts => new[]
    {
       OpenMirroringConfigurationConstants.WorkspaceName,
       OpenMirroringConfigurationConstants.MirroredDatabaseName,
       OpenMirroringConfigurationConstants.ClientId,
       OpenMirroringConfigurationConstants.TenantId,
    };

    public override async Task<CrawlJobData> GetCrawlJobData(
        ProviderUpdateContext context, IDictionary<string, object> configuration, Guid organizationId, Guid userId, Guid providerDefinitionId)
    {
        var data = await base.GetCrawlJobData(context, configuration, organizationId, userId, providerDefinitionId);

        if (data is CrawlJobDataWrapper wrapper)
        {
            var hasDatabaseName = wrapper.Configurations.TryGetValue(nameof(OpenMirroringConfigurationConstants.MirroredDatabaseName), out var dbName);
            if (hasDatabaseName && dbName is string dbNameString)
            {
                if (string.IsNullOrWhiteSpace(dbNameString))
                {
                    AddAutoGeneratedDatabaseName(providerDefinitionId, wrapper);
                }
                else
                {
                    TrimDatabaseName(wrapper, dbNameString);
                }
            }

            if (!hasDatabaseName)
            {
                AddAutoGeneratedDatabaseName(providerDefinitionId, wrapper);
            }

            var hasWorkspaceName = wrapper.Configurations.TryGetValue(nameof(OpenMirroringConfigurationConstants.WorkspaceName), out var workspaceName);

            if (hasWorkspaceName && workspaceName is string workspaceNameString)
            {
                TrimWorkspaceName(wrapper, workspaceNameString);
            }
        }

        return data;

        static void AddAutoGeneratedDatabaseName(Guid providerDefinitionId, CrawlJobDataWrapper wrapper)
        {
            wrapper.Configurations[nameof(OpenMirroringConfigurationConstants.MirroredDatabaseName)] = $"CluedIn_ExportTarget_{providerDefinitionId:N}";
        }

        static void TrimDatabaseName(CrawlJobDataWrapper wrapper, string dbNameString)
        {
            wrapper.Configurations[nameof(OpenMirroringConfigurationConstants.MirroredDatabaseName)] = dbNameString.Trim();
        }

        static void TrimWorkspaceName(CrawlJobDataWrapper wrapper, string workspaceNameString)
        {
            wrapper.Configurations[nameof(OpenMirroringConfigurationConstants.WorkspaceName)] = workspaceNameString?.Trim();
        }
    }
}
