<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <IgnoresAccessChecksTo Include="CluedIn.ComponentHealth" />
    <IgnoresAccessChecksTo Include="CluedIn.Streams" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IgnoresAccessChecksToGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Connector.Snowflake\Connector.Snowflake.csproj" />
  </ItemGroup>

</Project>
