<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="CluedIn.Connector.AmazonS3.Tests.Integration" />
    <InternalsVisibleTo Include="CluedIn.Connector.AzureDataLake.Tests.Integration" />
    <InternalsVisibleTo Include="CluedIn.Connector.OneLake.Tests.Integration" />
    <InternalsVisibleTo Include="CluedIn.Connector.FabricOpenMirroring.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Connector.DataLake.Common\Connector.DataLake.Common.csproj" />
    <ProjectReference Include="..\Connector.FileStorage.Common.Tests.Integration\Connector.FileStorage.Common.Tests.Integration.csproj" />
  </ItemGroup>

</Project>
