<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="CluedIn.Connector.AmazonS3.Tests.Integration" />
    <InternalsVisibleTo Include="CluedIn.Connector.AzureDataLake.Tests.Integration" />
    <InternalsVisibleTo Include="CluedIn.Connector.OneLake.Tests.Integration" />
    <InternalsVisibleTo Include="CluedIn.Connector.FabricOpenMirroring.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture.Xunit3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="Moq" />
    <PackageReference Include="IgnoresAccessChecksToGenerator" />
    <PackageReference Include="ParquetSharp" />
    <PackageReference Include="CsvHelper" />
  </ItemGroup>

  <ItemGroup>
    <IgnoresAccessChecksTo Include="CluedIn.ComponentHealth" />
    <IgnoresAccessChecksTo Include="CluedIn.Streams" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Connector.DataLake.Common\Connector.DataLake.Common.csproj" />
    <ProjectReference Include="..\Connector.FileStorage.Common.Tests.Integration\Connector.FileStorage.Common.Tests.Integration.csproj" />
  </ItemGroup>

</Project>
